Enable ServiceAccount annotations
aerokube/charts pull request #50
Opened 2021-04-09 08:01 UTC by huang-jy

This change request relates to https://github.com/aerokube/moon/issues/267 and will allow users to enable the moon service account to be used with Workload Identity (https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) or allow users to tag the service account with custom annotations which could be used for security or monitoring.

The annotations are not mandatory and no Moon functionality is changed by this PR being (or not being) merged.

One note: The current chart version available on the helm repo is 1.1.4, but the Chart.yaml in the git repo shows 1.0.7, I bumped the version to 1.1.5 for this change. If that is wrong, let me know and I'll put it down to 1.0.8

2021-04-09 12:50 UTC, vania-pooh requested changes
Please apply two straightforward fixes.

2021-04-09 12:50 UTC, vania-pooh commented on moon/Chart.yaml
> +version: 1.1.5
This change makes is useless. Version is being set automatically when deploying chart: https://github.com/aerokube/charts/blob/master/ci/build.sh#L13.

2021-04-09 12:50 UTC, vania-pooh commented on moon/templates/moon.yaml
> +  {{- if .Values.moon.serviceaccount.annotations }}
Need to check for null value:
```
{{- if and .Values.moon.serviceaccount .Values.moon.serviceaccount.annotations }}
```

2021-04-09 13:08 UTC, huang-jy commented on moon/templates/moon.yaml
> +  {{- if .Values.moon.serviceaccount.annotations }}
Ah yes, good catch

2021-04-09 16:23 UTC, vania-pooh approved these changes

2021-04-09 16:23 UTC, merged

2021-04-09 16:24 UTC, vania-pooh commented
@huang-jy thank you for contribution. These changes were automatically pushed to `aerokube-unstable` repository described in README.md. Would you need a stable version now?

2021-04-09 17:03 UTC, huang-jy commented
I can use the unstable version for testing the change. Will the change make
it into stable eventually? Or do I need to trigger something for that to
happen?

On Fri, 9 Apr 2021, 17:24 Ivan Krutov, ***@***.***> wrote:

> @huang-jy <https://github.com/huang-jy> thank you for contribution. These
> changes were automatically pushed to aerokube-unstable repository
> described in README.md. Would you need a stable version now?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/aerokube/charts/pull/50#issuecomment-816799541>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAVA5O2USSW44SESJP77VMTTH4S4LANCNFSM42UO7JDQ>
> .
>

2021-04-10 05:16 UTC, vania-pooh commented
@huang-jy we need to create a tag in this repo.

2021-04-10 06:39 UTC, huang-jy commented
Thanks, I'll test the change on the unstable, then let you know if it
behaves as expected. If so, we can then create the tag, or do whatever else
is necessary.

On Sat, 10 Apr 2021 at 06:16, Ivan Krutov ***@***.***> wrote:

> @huang-jy <https://github.com/huang-jy> we need to create a tag in this
> repo.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/aerokube/charts/pull/50#issuecomment-817080631>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAVA5OYRGVTB5BPBGDE4BMTTH7NMFANCNFSM42UO7JDQ>
> .
>

2021-04-11 09:53 UTC, huang-jy commented
Test successful. When installing the chart from stable with the annotation set to work with workload identity, then trying to use the workload test, it failed.

When installing from unstable, then running the same test, it worked.